---
kind: StaticAsset
format: json
name: kiwiconfig
object:
  windowTitle: {{apps.chat.windowTitle}}
  startupScreen: custom-welcome
  kiwiServer: https://localdev.clients.kiwiirc.com/webirc/kiwiirc/
  restricted: true
  theme: {{apps.chat.defaultTheme}}
  showColorPicker: true
  themes:
  - name: Default
    url: static/themes/default
  - name: Dark
    url: static/themes/dark
  - name: Coffee
    url: static/themes/coffee
  - name: GrayFox
    url: static/themes/grayfox
  - name: Nightswatch
    url: static/themes/nightswatch
  - name: Osprey
    url: static/themes/osprey
  - name: Radioactive
    url: static/themes/radioactive
  - name: Sky
    url: static/themes/sky
  - name: Elite
    url: static/themes/elite
  startupOptions:
    server: {{internal.apps.biziIrc.hostname.domain}}
    port: 6698
    toggablePassword: false
    channel: "{{apps.chat.defaultChannel}}"
    greetingText: {{apps.chat.greetingText}}
    nick: {{apps.chat.defaultNick}}
    direct: true
    tls: true
  buffers:
    who_loop: false
    nicklist_avatars: true
    extra_formatting: false
  embedly:
    key: ''
  plugins:
  - name: encryption-mac
    url: https://ipfs.io/ipns/kiwiiirc-plugins--encryption-mac.bizi.ly/plugin.js
    options:
      basePath: "https://ipfs.io/ipns/kiwiiirc-plugins--encryption-mac.bizi.ly/"
  - name: smart-chat-history
    url: https://ipfs.io/ipns/kiwiiirc-plugins--smart-chat-history.bizi.ly/plugin.js
